settings:
    font: -xos4-terminesspowerline-medium-r-normal--12-120-72-72-c-60-iso10646-1
    icon_font: -xos4-terminusicons2mono-medium-r-normal--12-120-72-72-m-60-iso8859-1
    default_tick: 10

colors:
    black: #073642
    grey: #002b36
    red: #dc322f
    lightred: #cb4b16
    green: #859900
    lightgreen: #586e75
    yellow: #b58900
    lightyellow: #657b83
    blue: #268bd2
    lightblue: #839496
    magenta: #d33682
    lightmagenta: #6c71c4
    cyan: #2aa198
    lightcyan: #93a1a1
    #white: #eee8d5
    white: #fdf6e3

styles:
    default:
        foreground: white
        background: black
    flashy:
        foreground: black
        background: green
    light:
        foreground: white
        background: grey
    urgent:
        foreground: white
        background: red
    disabled:
        foreground: grey
        background: black
    monitoring:
        foreground: black
        background: blue
    monitoring_urgent:
        foreground: black
        background: red
        separator: black

separators:
    left: 
    left_light: 
    right: 
    right_light: 

icons:
    clock: É
    cpu: Ñ
    memory: Î
    download: Ú
    upload: Û
    vol: Å
    hdd: ¦
    home: Æ
    mail: Ì
    chat: ©
    music: ê
    window: ¿
    contact: Á
    workspace: ö
    wlan: ­
    batt-empty: î
    batt-charging: ï
    batt-full: ð
    heat: ±

plugins:

    left:
        workspaces:
            plugin: i3-workspaces

        window:
            plugin: window
            truncate: 20
            options:
                icon: window

    right:
        hour:
            plugin: command
            tick: 60
            options:
                command: date '%a %d %b %Y'
                icon: clock
                nice: 20
                style: flashy

        volume:
            plugin: volume
            signal: 1
            options:
                icon: sound
                card: 0

        spacer:
            plugin: spacer
            tick: 0
            options:
                class: classic
                widescreen: true
                text: ~

        conky:
            plugin: conky
            options:
                eth: eth2
                wlan: wlan0

